# Generated by Django 2.2.6 on 2019-10-29 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Apellido')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='Celular')),
                ('cart_size', models.IntegerField(default=0, verbose_name='Pedidos que puede llevar')),
                ('orders_shipped', models.IntegerField(default=0)),
                ('orders_failure', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('address', models.CharField(default='', max_length=150, verbose_name='Dirección')),
                ('qty', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('observations', models.TextField(null=True, verbose_name='Observaciones')),
                ('order_type', models.CharField(choices=[('S', 'Salad'), ('B', 'Balance'), ('T', 'Temping')], max_length=1, verbose_name='Tipo de Pedido')),
                ('order_shift', models.CharField(choices=[('H1', 'Turno 1'), ('H2', 'Turno 2')], max_length=2, verbose_name='Turno')),
                ('delivery_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor.Delivery', verbose_name='Delivery:')),
            ],
        ),
    ]
