# Generated by Django 2.2.6 on 2019-10-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_forever',
            field=models.BooleanField(default=False, verbose_name='Es un pedido fijo?'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('B', 'Blanco'), ('En', 'Entregado'), ('Ca', 'Cancelado'), ('Ve', 'Verde'), ('R', 'Rojo'), ('Az', 'Azul'), ('Ro', 'Rosa'), ('Am', 'Amarillo')], default='B', max_length=2, verbose_name='Estado'),
        ),
    ]
