# Generated by Django 2.2.6 on 2019-12-07 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='Teléfono')),
                ('username', models.CharField(default='', max_length=50, unique=True, verbose_name='Username')),
                ('email', models.CharField(default='', max_length=50, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='Teléfono')),
                ('address', models.CharField(default='', max_length=50, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('is_forever', models.BooleanField(default=False, verbose_name='Es un menú fijo?')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del pedido')),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.Empleado', verbose_name='Empleado:')),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.Empresa', verbose_name='Empresa:')),
                ('id_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.Menu', verbose_name='Menú:')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.Empresa', verbose_name='Empresa:'),
        ),
    ]
